import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    TR: {

        catalog: "Katalog",
        my_quotes: "Teklif Taleplerim",
        settings: "Hesap Ayarları",
        logout: "Çıkış",
        back_to_catalog: "Kataloğa Dön",
        back_to_quotes: "Taleplerime Dön",
        individual: "Bireysel",
        seller: "Satıcı",
        buyer: "Alıcı",
        loading: "Yükleniyor...",
        close: "Kapat",
        approve: "Onayla",
        reject: "Reddet",
        cancel: "İptal",
        save: "Kaydet",
        ok: "Tamam",

        home_hero_badge: "Toptan Mobilya Ticaret Platformu",
        home_hero_title: "Mobilya Sektörünün Güvenilir B2B Pazaryeri",
        home_hero_desc: "Üreticiler ve mağazalar arasında doğrudan, şeffaf ve aracısız teklif usulü ticaret. Klasik sepet veya kredi kartı ödemeleri yok; sadece karşılıklı anlaşma ve kazançlı iş birliği var.",
        home_btn_start: "Hemen Başlayın ➔",
        home_btn_login: "Giriş Yap",
        home_stats_title: "APEX B2B Sayılarla Sektör",
        home_stats_desc: "Sektörün lider B2B pazaryerinde toptan mobilya ticaretinin gücünü keşfedin.",
        home_stat1_title: "Aktif Üye Şirket",
        home_stat1_desc: "Türkiye'nin dört bir yanından lider üreticiler ve seçkin mağazalar.",
        home_stat2_title: "Yıllık İşlem Hacmi",
        home_stat2_desc: "Hızlı fiyat teklifi ve doğrudan müzakere süreçleriyle toptan ciro.",
        home_stat3_title: "Müzakere Edilmiş Teklif",
        home_stat3_desc: "Ortalama 48 saat içinde sonuçlanan B2B toptan ticaret anlaşmaları.",
        home_feat1_title: "Firma (Satıcı) Profilleri",
        home_feat1_desc: "Mobilya üreticileri sisteme üye olarak kendi ürün kataloglarını yükler, fiyatları gizli tutarak teklif usulü satış yapar.",
        home_feat2_title: "Alıcı (Mağaza) Profilleri",
        home_feat2_desc: "Toptan alım yapmak isteyen mağazalar katalogları gezer, beğendikleri mobilyalar için özel fiyat teklifleri ister.",
        home_feat3_title: "Pazarlık ve Teklif Yönetimi",
        home_feat3_desc: "Fiyat teklifleri üzerinden satıcı ve alıcı panel üzerinden anlık olarak pazarlık yapar, fiyatları revize edip anlaşırlar.",
        home_flow_title: "Sistem Nasıl Çalışır?",
        home_flow_step1: "1. Profilinizi Açın",
        home_flow_step1_desc: "Satıcı Firma veya Alıcı Mağaza olarak profilinizi 2 dakikada tanımlayın.",
        home_flow_step2: "2. Kataloğu Gezin veya Yükleyin",
        home_flow_step2_desc: "Üreticiyseniz ürünlerinizi yükleyin, Alıcıysanız toptan katalogları keşfedin.",
        home_flow_step3: "3. Fiyat Teklifi İsteyin & Pazarlık Edin",
        home_flow_step3_desc: "Sepet veya ödeme yok! Fiyat Teklifi İste butonuyla satıcıyla pazarlık sürecini başlatın.",

        wizard_title: "Yeni B2B Hesabı Oluştur",
        wizard_role_title: "1. Aşama: Rolünüzü Seçin",
        wizard_role_desc: "Platformu ne amaçla kullanmak istediğinizi belirtin. Sonradan değiştiremezsiniz.",
        wizard_role_seller: "Satıcı Firma (Üretici)",
        wizard_role_seller_desc: "Mobilya üreticisiyim, ürünlerimi toptan pazarlamak ve mağazalardan teklif almak istiyorum.",
        wizard_role_buyer: "Alıcı Firma (Mağaza)",
        wizard_role_buyer_desc: "Toptan mobilya alımı yapmak isteyen bir perakende mağazası veya mobilya showroom'uyum.",
        wizard_basic_title: "2. Aşama: Hesap Giriş ve Kayıt Bilgileri",
        wizard_basic_desc: "Sisteme giriş yaparken kullanacağınız kişisel bilgilerinizi girin.",
        wizard_field_name: "Adınız Soyadınız",
        wizard_field_email: "E-Posta Adresiniz",
        wizard_field_phone: "Telefon Numaranız",
        wizard_field_password: "Güvenli Şifre",
        wizard_company_title: "3. Aşama: Şirket Marka Kurulumu",
        wizard_company_desc: "Müşterilerinize görünecek ticari firma profil bilgilerinizi doldurun.",
        wizard_field_company: "Firma / Marka Adı",
        wizard_field_about: "Firma Hakkında Kısa Bilgi",
        wizard_field_logo: "Firma Logo Adresi (URL)",
        wizard_success_title: "Tebrikler!",
        wizard_success_desc: "B2B profil kurulumunuz başarıyla tamamlandı. Artık sektöre hazırsınız!",
        wizard_btn_next: "Sonraki Adım ➔",
        wizard_btn_prev: "Geri",
        wizard_btn_finish: "Kurulumu Tamamla ✓",
        wizard_btn_close: "Platforma Giriş Yap",

        login_title: "B2B Giriş Paneli",
        login_subtitle: "Toptan Mobilya Ticaret Platformu",
        login_email: "Kayıtlı E-Posta Adresi",
        login_password: "Şifre",
        login_btn: "Giriş Yap",
        login_no_acc: "Hesabınız yok mu?",
        login_register_link: "Hemen Kaydolun",
        login_2fa_title: "İki Aşamalı Doğrulama (2FA)",
        login_2fa_subtitle: "Güvenliğiniz için lütfen telefonunuza veya mailinize gelen 6 haneli kodu girin.",
        login_2fa_code: "Doğrulama Kodu",
        login_2fa_code_placeholder: "Test kodu: 123456",
        login_2fa_btn: "Doğrula & Giriş Yap",
        login_2fa_cancel: "Vazgeç",

        register_title: "B2B Kayıt Paneli",
        register_subtitle: "Toptan Mobilya Ticaret Platformu",
        register_name: "Adınız Soyadınız",
        register_email: "E-Posta Adresi",
        register_phone: "Telefon Numarası",
        register_password: "Şifre",
        register_company: "Firma / Şirket Adı",
        register_btn: "Hesap Oluştur",
        register_has_acc: "Zaten üye misiniz?",
        register_login_link: "Giriş Yapın",

        dash_welcome: "Hoş Geldiniz",
        dash_stats_products: "Katalog Ürünleri",
        dash_stats_role: "Hesap Yetkisi",
        dash_stats_role_seller: "Mobilya Üreticisi",
        dash_stats_role_admin: "Sistem Yöneticisi",
        dash_stats_role_buyer: "Mağaza Alıcısı",
        dash_stats_quotes: "Aktif Teklif Talepleri",
        dash_search_placeholder: "Ürün adı, detay veya üretici firma ara...",
        dash_category_all: "Tüm Kategoriler",
        dash_category_living: "Oturma Odası (Living Room)",
        dash_category_dining: "Yemek Odası (Dining Room)",
        dash_category_bedroom: "Yatak Odası (Bedroom)",
        dash_category_office: "Ofis Mobilyaları (Office)",
        dash_manage_listings: "İlanlarımı Yönet",
        dash_tour_btn_start: "Tur Rehberini Yeniden Başlat",
        dash_btn_request_quote: "Teklif İstenebilir",

        tour_step1_badge: "Adım 1/3: Üst Menü Gezinme",
        tour_step1_title: "Portalda Gezinin",
        tour_step1_desc: "Sitenin ana menüsünü kullanarak Katalog sayfasından mobilya modellerini inceleyebilir, Teklif Taleplerim alanından ise tüm fiyat müzakerelerinizi anlık takip edebilirsiniz.",
        tour_step2_badge: "Adım 2/3: Akıllı Filtreleme",
        tour_step2_title: "Kataloğu Keşfedin",
        tour_step2_desc: "Gelişmiş arama çubuğu ve kategori seçicileri kullanarak binlerce mobilya modelini anında süzebilir, dilediğiniz mobilyaları hızla bulabilirsiniz.",
        tour_step3_badge: "Adım 3/3: B2B Fiyat Pazarlığı",
        tour_step3_title: "Toptan Teklif Süreci",
        tour_step3_desc: "Beğendiğiniz mobilyaya tıklayarak detayına gidin. 'Fiyat Teklifi İste' butonu sayesinde doğrudan üretici ile chat üzerinden B2B pazarlık başlatabilirsiniz.",

        detail_manufacturer: "ÜRETİCİ",
        detail_dimensions: "Boyutlar",
        detail_collection: "Koleksiyon",
        detail_variants_title: "Renk Varyantları (Galeri Filtresi)",
        detail_variants_note: "* Seçtiğiniz renge göre sol taraftaki ürün resimleri otomatik güncellenir.",
        detail_negotiation_info: "FİYAT GÖRÜŞMELERİ PAZARLIK YÖNETİMİNDEN İLERLER",
        detail_btn_request_quote: "Fiyat Teklifi İste",
        detail_modal_title: "Fiyat Teklif Talebi Gönder",
        detail_modal_subtitle: "Üretici firmadan bu ürün için toptan fiyat ve teslimat detayları isteyin",
        detail_modal_notes_label: "Fiyat Talebi Notlarınız / İstedikleriniz (Adet vb.)",
        detail_modal_notes_placeholder: "Örn: Bu üründen Zümrüt Yeşili renginde 20 adet almak istiyoruz. İstanbul teslimatlı fiyat teklifinizi ve teslim sürenizi iletebilir misiniz?",
        detail_modal_btn_send: "Teklif Talebi Gönder ➔",

        quotes_title: "B2B Fiyat Görüşmelerim",
        quotes_subtitle: "Satıcı ve alıcı arasındaki aktif pazarlık ve teklif yönetimi süreçleri",
        quotes_header_product: "Ürün / İlan",
        quotes_header_party: "Muhatap Firma",
        quotes_header_last_price: "Son Önerilen Fiyat",
        quotes_header_status: "Durum",
        quotes_header_action: "Detaylar",
        quotes_status_pending: "Teklif Bekliyor",
        quotes_status_negotiation: "Pazarlık Yapılıyor",
        quotes_status_approved: "Kabul Edildi",
        quotes_status_rejected: "Reddedildi",
        quotes_party_seller: "Satıcı Şirket",
        quotes_party_buyer: "Alıcı Şirket",
        quotes_btn_view: "Görüşmeyi Aç ➔",
        quotes_no_data: "Henüz hiçbir fiyat teklif talebi bulunmamaktadır.",

        qdetail_title: "B2B Pazarlık & Görüşme Paneli",
        qdetail_sidebar_info: "Teklif Detayları",
        qdetail_sidebar_product: "Ürün",
        qdetail_sidebar_category: "Kategori",
        qdetail_sidebar_seller: "Satıcı Üretici",
        qdetail_sidebar_buyer: "Alıcı Mağaza",
        qdetail_sidebar_last_proposal: "Son Fiyat Önerisi",
        qdetail_sidebar_status: "Müzakere Durumu",
        qdetail_chat_title: "Karşılıklı Pazarlık Chat Ekranı",
        qdetail_chat_subtitle: "Mesajlaşma ve Anlık Fiyat Revizyonları",
        qdetail_propose_title: "Yeni Fiyat Teklifi Öner",
        qdetail_propose_btn: "Fiyat Öner",
        qdetail_propose_placeholder: "Örn: 12500",
        qdetail_chat_placeholder: "Bir mesaj yazın...",
        qdetail_action_confirm: "Teklifi Kabul Et",
        qdetail_action_reject: "Teklifi Reddet",
        qdetail_status_alert_approved: "🎉 Bu teklif karşılıklı olarak KABUL EDİLDİ.",
        qdetail_status_alert_rejected: "❌ Bu teklif REDDEDİLDİ.",

        settings_title: "Hesap Bilgileri & Güvenlik",
        settings_subtitle: "İsim soy isim harici bilgilerinizi güncelleyin",
        settings_avatar_label: "Kişisel Profil Fotoğrafı",
        settings_avatar_desc: "Bilgisayarınızdan bir portre görseli seçip yükleyin.",
        settings_pending_box_title: "⏳ ONAY BEKLEYEN DEĞİŞİKLİKLER",
        settings_pending_email: "Yeni E-Posta Talebi",
        settings_pending_phone: "Yeni Telefon Talebi",
        settings_pending_note: "* Sistem yöneticisi inceledikten sonra değişiklik aktif olacaktır.",
        settings_field_name: "Adınız Soyadınız (Değiştirilemez)",
        settings_field_email: "Kişisel E-Posta Adresi",
        settings_field_phone: "Kişisel Telefon Numarası",
        settings_btn_save_personal: "Kişisel Bilgileri Kaydet",
        settings_sec_title: "Güvenlik ve Tercihler",
        settings_sec_subtitle: "İki aşamalı doğrulama ve ses ayarlarını yönetin",
        settings_2fa_label: "İki Aşamalı Doğrulama (2FA)",
        settings_2fa_desc: "Giriş yaparken 6 haneli doğrulama kodu girmeyi zorunlu kıl.",
        settings_sound_label: "Sesli Bildirim Uyarıları",
        settings_sound_desc: "Yeni teklif ve mesaj geldiğinde ses çal.",
        settings_email_alerts_label: "E-Posta Bildirim Uyarıları",
        settings_email_alerts_desc: "Önemli gelişmeler e-posta kutuma gönderilsin.",
        settings_company_title: "Kurumsal Şirket Profili",
        settings_company_subtitle: "Müşterilerinize görünecek kurumsal ve doğrulanmış firma kimliği",
        settings_logo_label: "Kurumsal Logo Resmi",
        settings_logo_desc: "Bilgisayardan firma logonuzu seçip yükleyin.",
        settings_field_company_name: "Şirket / Marka Ticari Adı",
        settings_company_email_label: "Kurumsal Firma E-Postası",
        settings_company_phone_label: "Kurumsal Firma Telefonu",
        settings_verified: "Doğrulanmış",
        settings_unverified: "Doğrulanmamış",
        settings_btn_verify: "Doğrula",
        settings_field_about: "Firma Tanıtımı / Hakkında Yazısı",
        settings_btn_save_company: "Kurumsal Bilgileri Kaydet",
        settings_listings_title: "İlan Yönetim Paneli",
        settings_listings_subtitle: "Kataloğunuzdaki ilanları düzenleyin, pasife alın veya silin",
        settings_btn_add_product: "Yeni İlan Ekle",
        settings_listings_empty: "Henüz yüklenmiş bir ilanınız bulunmamaktadır. Sağ üstten hemen ilk ilanınızı ekleyin!",
        settings_listings_status_active: "Yayında",
        settings_listings_status_passive: "Pasif",
        settings_listings_colors_label: "Renkler",
        settings_listings_edit_title: "İlanı Düzenle",
        settings_listings_add_title: "Kataloğa Yeni Mobilya Ekle",
        settings_listings_desc_modal: "Müşterileriniz fiyat teklifi isteyebilecektir",
        settings_field_pname: "Ürün Adı",
        settings_field_pcategory: "Kategori",
        settings_field_pdescription: "Açıklama & Malzeme Özellikleri",
        settings_field_pdimensions: "Boyutlar (Genişlik x Derinlik x Yükseklik)",
        settings_listings_colors_section: "Renk Seçenekleri Ekle",
        settings_listings_btn_add_color: "Renk Ekle",
        settings_listings_color_input_placeholder: "Renk adı girin (Örn: Haki Yeşil)",
        settings_listings_added_colors_label: "Eklenen Renkler",
        settings_listings_color_mgmt: "Rengi İçin Resim Yönetimi",
        settings_listings_choose_files: "Bilgisayardan Resim Seçin",
        settings_listings_uploaded_images: "Yüklenen Resimler",
        settings_listings_btn_save_prod: "İlanı Kaydet",
        settings_admin_title: "Yönetici Profil Onayları",
        settings_admin_subtitle: "Kullanıcıların onay bekleyen e-posta ve telefon değişiklik talepleri",
        settings_admin_empty: "Onay bekleyen hiçbir profil değişiklik talebi bulunmamaktadır.",
        settings_admin_email_change: "E-Posta Değişimi",
        settings_admin_phone_change: "Telefon Değişimi",
        settings_admin_btn_approve: "Onayla",
        settings_admin_btn_reject: "Reddet",
        settings_tab_personal: "Kişisel Profilim & Güvenlik",
        settings_tab_company: "Kurumsal Firma Profili",
        settings_tab_listings: "İlanlarım & Katalog",
        settings_tab_admin: "Yönetici Onayları",
        settings_verification_title: "Firma Kimlik Doğrulaması",
        settings_verification_subtitle: "Güvenli SMS & E-Posta Doğrulama Sistemi",
        settings_verification_code_sent: "Doğrulama Kodu Gönderildi!",
        settings_verification_code_sent_desc: "ile geçici bir onay kodu gönderilmiştir.",
        settings_verification_test_code_note: "* Test kodu: 123456",
        settings_verification_btn_verify: "Onayla",
        settings_verification_btn_close: "Kapat"
    },
    EN: {

        catalog: "Catalog",
        my_quotes: "My Quote Requests",
        settings: "Account Settings",
        logout: "Logout",
        back_to_catalog: "Back to Catalog",
        back_to_quotes: "Back to Requests",
        individual: "Individual",
        seller: "Seller",
        buyer: "Buyer",
        loading: "Loading...",
        close: "Close",
        approve: "Approve",
        reject: "Reject",
        cancel: "Cancel",
        save: "Save",
        ok: "OK",

        home_hero_badge: "Wholesale Furniture Trade Platform",
        home_hero_title: "The Trusted B2B Furniture Marketplace",
        home_hero_desc: "Direct, transparent, and intermediary-free quote-based trade between manufacturers and stores. No traditional shopping carts or credit card payments; only mutual agreement and profitable cooperation.",
        home_btn_start: "Get Started Now ➔",
        home_btn_login: "Login",
        home_stats_title: "APEX B2B Industry in Numbers",
        home_stats_desc: "Discover the power of wholesale furniture trade in the industry's leading B2B marketplace.",
        home_stat1_title: "Active Member Companies",
        home_stat1_desc: "Leading manufacturers and distinguished stores from all over the country.",
        home_stat2_title: "Annual Transaction Volume",
        home_stat2_desc: "Wholesale turnover backed by fast price quotes and direct negotiation.",
        home_stat3_title: "Negotiated Quotes",
        home_stat3_desc: "B2B wholesale trade agreements concluded in 48 hours on average.",
        home_feat1_title: "Company (Seller) Profiles",
        home_feat1_desc: "Furniture manufacturers register to upload catalogs and sell on a quote basis with hidden prices.",
        home_feat2_title: "Buyer (Store) Profiles",
        home_feat2_desc: "Retail stores looking for wholesale purchases browse catalogs and request custom price quotes.",
        home_feat3_title: "Negotiation & Quote Management",
        home_feat3_desc: "Sellers and buyers negotiate quote prices in real-time, revise offers, and reach agreements.",
        home_flow_title: "How It Works?",
        home_flow_step1: "1. Create Your Profile",
        home_flow_step1_desc: "Set up your profile as a Seller Company or Buyer Store in 2 minutes.",
        home_flow_step2: "2. Browse or Upload Products",
        home_flow_step2_desc: "Upload items if you are a manufacturer, or explore wholesale catalogs if you are a buyer.",
        home_flow_step3: "3. Request Quote & Negotiate",
        home_flow_step3_desc: "No checkout carts or payments! Start negotiations with the manufacturer via 'Request Quote'.",

        wizard_title: "Create New B2B Account",
        wizard_role_title: "Step 1: Choose Your Role",
        wizard_role_desc: "Specify how you plan to use the platform. This cannot be changed later.",
        wizard_role_seller: "Seller Company (Manufacturer)",
        wizard_role_seller_desc: "I am a furniture manufacturer who wants to market products wholesale and receive store quotes.",
        wizard_role_buyer: "Buyer Company (Store)",
        wizard_role_buyer_desc: "I am a retail store or furniture showroom looking to purchase wholesale furniture.",
        wizard_basic_title: "Step 2: Account Login & Details",
        wizard_basic_desc: "Enter your personal credentials to log into the platform.",
        wizard_field_name: "Full Name",
        wizard_field_email: "E-mail Address",
        wizard_field_phone: "Phone Number",
        wizard_field_password: "Secure Password",
        wizard_company_title: "Step 3: Company Setup",
        wizard_company_desc: "Fill in the commercial profile details that will be visible to your customers.",
        wizard_field_company: "Company / Brand Name",
        wizard_field_about: "Brief Company Description",
        wizard_field_logo: "Company Logo URL",
        wizard_success_title: "Congratulations!",
        wizard_success_desc: "Your B2B profile setup has been successfully completed. You are ready for the market!",
        wizard_btn_next: "Next Step ➔",
        wizard_btn_prev: "Back",
        wizard_btn_finish: "Complete Setup ✓",
        wizard_btn_close: "Enter Platform",

        login_title: "B2B Login Panel",
        login_subtitle: "Wholesale Furniture Trade Platform",
        login_email: "Registered E-mail Address",
        login_password: "Password",
        login_btn: "Login",
        login_no_acc: "Don't have an account?",
        login_register_link: "Register Now",
        login_2fa_title: "Two-Factor Authentication (2FA)",
        login_2fa_subtitle: "For your security, please enter the 6-digit code sent to your phone or e-mail.",
        login_2fa_code: "Verification Code",
        login_2fa_code_placeholder: "Test code: 123456",
        login_2fa_btn: "Verify & Log In",
        login_2fa_cancel: "Cancel",

        register_title: "B2B Register Panel",
        register_subtitle: "Wholesale Furniture Trade Platform",
        register_name: "Full Name",
        register_email: "E-mail Address",
        register_phone: "Phone Number",
        register_password: "Password",
        register_company: "Company / Brand Name",
        register_btn: "Create Account",
        register_has_acc: "Already a member?",
        register_login_link: "Login Here",

        dash_welcome: "Welcome",
        dash_stats_products: "Catalog Products",
        dash_stats_role: "Account Authorization",
        dash_stats_role_seller: "Furniture Manufacturer",
        dash_stats_role_admin: "System Administrator",
        dash_stats_role_buyer: "Store Buyer",
        dash_stats_quotes: "Active Quote Requests",
        dash_search_placeholder: "Search product name, description or manufacturer...",
        dash_category_all: "All Categories",
        dash_category_living: "Living Room",
        dash_category_dining: "Dining Room",
        dash_category_bedroom: "Bedroom",
        dash_category_office: "Office Furniture",
        dash_manage_listings: "Manage Listings",
        dash_tour_btn_start: "Restart Tour Guide",
        dash_btn_request_quote: "Can Request Quote",

        tour_step1_badge: "Step 1/3: Navbar Navigation",
        tour_step1_title: "Navigate the Portal",
        tour_step1_desc: "Use the top menu to view furniture models in the Catalog, or track all your active price negotiations in the Quote Requests section.",
        tour_step2_badge: "Step 2/3: Smart Filters",
        tour_step2_title: "Explore the Catalog",
        tour_step2_desc: "Filter thousands of furniture models instantly using the advanced search bar and category selectors to find the exact items you need.",
        tour_step3_badge: "Step 3/3: B2B Price Negotiation",
        tour_step3_title: "Wholesale Quote Process",
        tour_step3_desc: "Click on any furniture model to view details. Use the 'Request Price' button to initiate direct B2B chat negotiations with the manufacturer.",

        detail_manufacturer: "MANUFACTURER",
        detail_dimensions: "Dimensions",
        detail_collection: "Collection",
        detail_variants_title: "Color Variants (Gallery Filter)",
        detail_variants_note: "* Product gallery automatically updates based on selected color.",
        detail_negotiation_info: "PRICE NEGOTIATIONS ARE MANAGED DIRECTLY VIA PORTAL CHAT",
        detail_btn_request_quote: "Request Price Quote",
        detail_modal_title: "Submit Price Quote Request",
        detail_modal_subtitle: "Request wholesale prices and shipping details for this model from the manufacturer",
        detail_modal_notes_label: "Your Request Notes / Special Requirements (Quantity etc.)",
        detail_modal_notes_placeholder: "e.g. We are interested in purchasing 20 units of this model in Emerald Green. Can you provide a wholesale quote delivered to Chicago and specify lead time?",
        detail_modal_btn_send: "Send Quote Request ➔",

        quotes_title: "My B2B Price Negotiations",
        quotes_subtitle: "Active bargaining and price negotiation histories between sellers and buyers",
        quotes_header_product: "Product / Listing",
        quotes_header_party: "Counterpart Company",
        quotes_header_last_price: "Last Proposed Price",
        quotes_header_status: "Status",
        quotes_header_action: "Details",
        quotes_status_pending: "Awaiting Quote",
        quotes_status_negotiation: "In Negotiation",
        quotes_status_approved: "Approved",
        quotes_status_rejected: "Rejected",
        quotes_party_seller: "Seller Company",
        quotes_party_buyer: "Buyer Company",
        quotes_btn_view: "Open Discussion ➔",
        quotes_no_data: "No price quote requests have been initiated yet.",

        qdetail_title: "B2B Negotiation Panel",
        qdetail_sidebar_info: "Quote Details",
        qdetail_sidebar_product: "Product",
        qdetail_sidebar_category: "Category",
        qdetail_sidebar_seller: "Seller Manufacturer",
        qdetail_sidebar_buyer: "Buyer Store",
        qdetail_sidebar_last_proposal: "Last Price Proposal",
        qdetail_sidebar_status: "Negotiation Status",
        qdetail_chat_title: "Bargaining Chat Room",
        qdetail_chat_subtitle: "Messaging and Real-time Price Revisions",
        qdetail_propose_title: "Propose a New Price",
        qdetail_propose_btn: "Submit Offer",
        qdetail_propose_placeholder: "e.g. 12500",
        qdetail_chat_placeholder: "Type a message...",
        qdetail_action_confirm: "Accept Offer",
        qdetail_action_reject: "Reject Offer",
        qdetail_status_alert_approved: "🎉 This offer has been mutually APPROVED.",
        qdetail_status_alert_rejected: "❌ This offer was REJECTED.",

        settings_title: "Account Info & Security",
        settings_subtitle: "Manage details other than full name",
        settings_avatar_label: "Personal Profile Avatar",
        settings_avatar_desc: "Choose and upload a portrait photo from your computer.",
        settings_pending_box_title: "⏳ PENDING CHANGES AWAITING APPROVAL",
        settings_pending_email: "New Email Request",
        settings_pending_phone: "New Phone Request",
        settings_pending_note: "* Updates will take effect once reviewed by the administrator.",
        settings_field_name: "Full Name (Read-only)",
        settings_field_email: "Personal Email Address",
        settings_field_phone: "Personal Phone Number",
        settings_btn_save_personal: "Save Personal Info",
        settings_sec_title: "Security and Preferences",
        settings_sec_subtitle: "Manage two-factor auth and notification sound alerts",
        settings_2fa_label: "Two-Factor Authentication (2FA)",
        settings_2fa_desc: "Enforce a 6-digit verification code when logging in.",
        settings_sound_label: "Sound Alerts",
        settings_sound_desc: "Play sound alerts when new quotes or messages arrive.",
        settings_email_alerts_label: "Email Notifications",
        settings_email_alerts_desc: "Receive email notifications for important system events.",
        settings_company_title: "Corporate Company Profile",
        settings_company_subtitle: "Verified commercial profile details visible to your clients",
        settings_logo_label: "Corporate Logo Image",
        settings_logo_desc: "Select and upload your company logo from your PC.",
        settings_field_company_name: "Company / Brand Commercial Name",
        settings_company_email_label: "Company Email",
        settings_company_phone_label: "Company Phone",
        settings_verified: "Verified",
        settings_unverified: "Unverified",
        settings_btn_verify: "Verify",
        settings_field_about: "Company Bio / Description",
        settings_btn_save_company: "Save Corporate Info",
        settings_listings_title: "Listing Management",
        settings_listings_subtitle: "Create, edit, toggle status or delete items in your catalog",
        settings_btn_add_product: "Add New Listing",
        settings_listings_empty: "You don't have any product listings. Click on top right to add your first item!",
        settings_listings_status_active: "Active",
        settings_listings_status_passive: "Passive",
        settings_listings_colors_label: "Colors",
        settings_listings_edit_title: "Edit Listing",
        settings_listings_add_title: "Add New Furniture to Catalog",
        settings_listings_desc_modal: "Customers will be able to request B2B price quotes for this item",
        settings_field_pname: "Product Name",
        settings_field_pcategory: "Category",
        settings_field_pdescription: "Description & Material Specs",
        settings_field_pdimensions: "Dimensions (W x D x H)",
        settings_listings_colors_section: "Add Color Variants",
        settings_listings_btn_add_color: "Add Color",
        settings_listings_color_input_placeholder: "Enter color name (e.g. Emerald Green)",
        settings_listings_added_colors_label: "Added Colors",
        settings_listings_color_mgmt: "Image Management for Color",
        settings_listings_choose_files: "Select Images from Computer",
        settings_listings_uploaded_images: "Uploaded Images",
        settings_listings_btn_save_prod: "Save Listing",
        settings_admin_title: "Admin Approvals Board",
        settings_admin_subtitle: "Approve or reject user pending email and phone changes",
        settings_admin_empty: "No profile updates are currently awaiting admin review.",
        settings_admin_email_change: "Email Update",
        settings_admin_phone_change: "Phone Update",
        settings_admin_btn_approve: "Approve",
        settings_admin_btn_reject: "Reject",
        settings_tab_personal: "Personal Profile & Security",
        settings_tab_company: "Corporate Profile",
        settings_tab_listings: "My Listings & Catalog",
        settings_tab_admin: "Admin Board",
        settings_verification_title: "Company Identification Verification",
        settings_verification_subtitle: "Secure SMS & Email Verification System",
        settings_verification_code_sent: "Verification Code Sent!",
        settings_verification_code_sent_desc: "A temporary code has been sent to",
        settings_verification_test_code_note: "* Test code: 123456",
        settings_verification_btn_verify: "Verify",
        settings_verification_btn_close: "Close"
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLangState] = useState(localStorage.getItem('apex_lang') || 'TR');

    const changeLanguage = (lang) => {
        setLangState(lang);
        localStorage.setItem('apex_lang', lang);
    };

    const t = (key) => {
        const trans = translations[language];
        return trans[key] || translations['TR'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
